### get company

GET http://localhost:3000/api/companies


### get company by order lowestInvestment
GET http://localhost:3000/api/companies?orderBy=lowestInvestment

### get company by order highestInvestment

GET http://localhost:3000/api/companies?orderBy=highestInvestment


### get company by order highestRevenue

GET http://localhost:3000/api/companies?orderBy=highestRevenue

### get company by order lowestRevenue

GET http://localhost:3000/api/companies?orderBy=lowestRevenue

### get company by order highestEmployees

GET http://localhost:3000/api/companies?orderBy=highestEmployees

### get company by order lowestEmployees

GET http://localhost:3000/api/companies?orderBy=lowestEmployees


### get company by keyword

GET http://localhost:3000/api/companies?orderBy=lowestEmployees&keyword=마켓



### get company by id

GET http://localhost:3000/api/companies/1bc0569d-8bfd-49d5-b44c-c17f13c97af2